<?php //Terms.php - no actual php on this page ?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../images/favicon.ico">
    <title>Jersey Flatshare - Site Terms of Use</title>
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/flatshare.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top customColor">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="../index.php">Jersey Flatshare</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="../index.php#flatshares">Flatshares</a></li>
            <li><a href="../index.php#about">About Us</a></li>
            <li><a href="../index.php#contact">Contact Us</a></li>
          </ul>
        </div>
      </div>
    </nav>
      <!-- Begin page content -->
      <div class="container">
            <h3>Website Terms of Use</h3>
            <p class="text-justify">Our terms of use our quite simple really.  This website is for landlords to advertise rooms in houses or flats for rent, on the Island of Jersey.  This website is also for people looking to rent a room in a house or flat on the island of Jersey.</p>

            <p class="text-justify">This website only provides a way for the two parties to find each other free of charge.  This website <strong>does not</strong> provide any vetting of landlords or tenants, or provide any property management.  Landlords and tenants are responsible for any terms of rental and once a landlord and prospective tenant have made contact with each other this website (and by extension us) has no further involvement in the process.</p>

            <p class="text-justify">Landlords <strong>must</strong> ensure they <strong>comply fully</strong> with all relevant local legislation with regard to the renting of rooms in properties, including the correct handling of deposit monies.</p>
          
            <p class="text-justify">When viewing properties please take all the usual precautions, if possible don’t visit properties on your own, and always tell someone where you are going and when.  We are not in anyway responsible for the safety of either landlord or prospective tenant through the use of this site.</p>
          
            <p class="text-justify">This site makes use of cookies, both session cookies which enhance your site user experience, and also cookies generated by google as part of their website analytics program.  We do not make any use of the data contained in cookies generated by us once you have left this site.</p>
          
            <p class="text-justify">The following below website disclaimer sets out in full everything else not covered by the above statements.</p>
          
            <div class="well extraTopMargin">
                <h4 class="text-center">Website disclaimer</h4>
                <p class="small">1. Introduction</p>
                <p  class="small tab">1.1 This disclaimer shall govern your use of our website.</p>
                <p  class="small tab">1.2 By using our website, you accept this disclaimer in full; accordingly, if you disagree with this disclaimer or any part of this disclaimer, you must not use our website.</p>
                <p class="small">2. Credit</p>
                <p  class="small tab">2.1 This document was created using a template from SEQ Legal (http://www.seqlegal.com).</p>
                <p class="small">3. Copyright notice</p>
                <p  class="small tab">3.1 Copyright (c) 2016 Jersey Flatshare.</p>
                <p  class="small tab">3.2 Subject to the express provisions of this disclaimer:</p>
                <p class="small tabB">(a) we, together with our licensors, own and control all the copyright and other intellectual property rights in our website and the material on our website; and</p>
                <p class="small tabB">(b) all the copyright and other intellectual property rights in our website and the material on our website are reserved.</p>
                <p class="small">4. Licence to use website</p>
                    <p  class="small tab">4.1 You may:</p>
                        <p class="small tabB">(a) view pages from our website in a web browser;</p>
                        <p class="small tabB">(b) download pages from our website for caching in a web browser; and</p>
                        <p class="small tabB">(c) print pages from our website, subject to the other provisions of this disclaimer.</p>
                    <p class="small tab">4.2 Except as expressly permitted by Section 4.1 or the other provisions of this disclaimer, you must not download any material from our website or save any such material to your computer.</p>
                    <p class="small tab">4.3 You may only use our website for the advertising of rooms in houses or flats on the island of Jersey that you own or legally manage, or to find rooms in houses or flats on the island of Jersey, and you must not use our website for any other purposes.</p>
                    <p class="small tab">4.4 Unless you own or control the relevant rights in the material, you must not:</p>
                        <p class="small tabB">(a) republish material from our website (including republication on another website);</p>
                        <p class="small tabB">(b) sell, rent or sub-license material from our website;</p>
                        <p class="small tabB">(c) show any material from our website in public;</p>
                        <p class="small tabB">(d) exploit material from our website for a commercial purpose; or</p>
                        <p class="small tabB">(e) redistribute material from our website.</p>
                    <p  class="small tab">4.5 We reserve the right to restrict access to areas of our website, or indeed our whole website, at our discretion; you must not circumvent or bypass, or attempt to circumvent or bypass, any access restriction measures on our website.</p>
                <p class="small">5. Acceptable use</p>
                    <p  class="small tab">5.1 You must not:</p>
                        <p class="small tabB">(a)	use our website in any way or take any action that causes, or may cause, damage to the website or impairment of the performance, availability or accessibility of the website;</p>
                        <p class="small tabB">(b)	use our website in any way that is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity;</p>
                        <p class="small tabB">(c)   make listings to this website that contain offensive language, or images that contain offensive material.</p>
                        <p class="small tabB">(d)	use our website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software;</p>
                        <p class="small tabB">(e)	conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to our website without our express written consent;</p>
             </div>  
      </div>  

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Jersey Flatshare &copy;2016 | <a href="terms.php">Click Here for The Legal Bit</a> </p>
      </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="../js/jquery-1.11.3.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
    <script src="../js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
